### ISSUE TITLE
T-spin rewards

### ISSUE THREAD

**Issue by deadbeef84** [deadbeef84/tetrinet#9]
http://tetris.wikia.com/wiki/T-Spin_Guide

**Comment by dwyfl** [comment]
T-spin is now supported, however only possible with SRS except for very basic moves. Also, there seem to be lots of different models of how t-spins are rewarded, I guess this should be tested/discussed. For now, each line completed by a t-spin sends two lines to the opponents, and there is also a back-to-back bonus of 1 line.
